# Generated by Django 3.2.9 on 2021-12-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64,
                 unique=True, verbose_name='имя')),
                ('description', models.TextField(
                    blank=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='имя продукта')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_desc', models.CharField(blank=True, max_length=64,
                 verbose_name='краткое описание продукта')),
                ('description', models.TextField(
                    blank=True, verbose_name='описание продукта')),
                ('price', models.DecimalField(decimal_places=2,
                 default=0, max_digits=8, verbose_name='цена продукта')),
                ('quantity', models.PositiveIntegerField(
                    default=0, verbose_name='количество продукта')),
                ('category', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.productcategory')),
            ],
        ),
    ]
